name = "lean-action"
version = "0.1.0"
defaultTargets = ["LeanAction", "LeanActionExamples", "LeanActionTests"]

[[lean_lib]]
name = "LeanAction"
globs = ["LeanAction", "LeanAction.+"]
roots = ["LeanAction"]

[[lean_lib]]
name = "LeanActionExamples"
globs = ["Examples"]
roots = ["Examples"]

[[lean_lib]]
name = "LeanActionTests"
globs = ["Tests", "Tests.+"]
roots = ["Tests"]
